baseURL = "http://example.org/"
languageCode = "utf-8"
title = "Bunshinn's page"


theme = "bs-blog"


[params]
    mainSections = ["posts",] 
    doc = "/doc"
	tag = "tags"
	category = "categories"

